return {
    { code = "ad", name = "andorra", file = "ad.png" },
    { code = "ae", name = "united arab emirates", file = "ae.png" },
    { code = "af", name = "afghanistan", file = "af.png" },
    { code = "ag", name = "antigua and barbuda", file = "ag.png" },
    { code = "ai", name = "anguilla", file = "ai.png" },
    { code = "al", name = "albania", file = "al.png" },
    { code = "am", name = "armenia", file = "am.png" },
    { code = "ao", name = "angola", file = "ao.png" },
    { code = "aq", name = "antarctica", file = "aq.png" },
    { code = "ar", name = "argentina", file = "ar.png" },
    { code = "as", name = "american samoa", file = "as.png" },
    { code = "at", name = "austria", file = "at.png" },
    { code = "au", name = "australia", file = "au.png" },
    { code = "aw", name = "aruba", file = "aw.png" },
    { code = "ax", name = "åland islands", file = "ax.png" },
    { code = "az", name = "azerbaijan", file = "az.png" },
    { code = "ba", name = "bosnia and herzegovina", file = "ba.png" },
    { code = "bb", name = "barbados", file = "bb.png" },
    { code = "bd", name = "bangladesh", file = "bd.png" },
    { code = "be", name = "belgium", file = "be.png" },
    { code = "bf", name = "burkina faso", file = "bf.png" },
    { code = "bg", name = "bulgaria", file = "bg.png" },
    { code = "bh", name = "bahrain", file = "bh.png" },
    { code = "bi", name = "burundi", file = "bi.png" },
    { code = "bj", name = "benin", file = "bj.png" },
    { code = "bl", name = "saint barthélemy", file = "bl.png" },
    { code = "bm", name = "bermuda", file = "bm.png" },
    { code = "bn", name = "brunei", file = "bn.png" },
    { code = "bo", name = "bolivia", file = "bo.png" },
    { code = "bq", name = "caribbean netherlands", file = "bq.png" },
    { code = "br", name = "brazil", file = "br.png" },
    { code = "bs", name = "bahamas", file = "bs.png" },
    { code = "bt", name = "bhutan", file = "bt.png" },
    { code = "bv", name = "bouvet island", file = "bv.png" },
    { code = "bw", name = "botswana", file = "bw.png" },
    { code = "by", name = "belarus", file = "by.png" },
    { code = "bz", name = "belize", file = "bz.png" },
    { code = "ca", name = "canada", file = "ca.png" },
    { code = "cc", name = "cocos (keeling) islands", file = "cc.png" },
    { code = "cd", name = "dr congo", file = "cd.png" },
    { code = "cf", name = "central african republic", file = "cf.png" },
    { code = "cg", name = "republic of the congo", file = "cg.png" },
    { code = "ch", name = "switzerland", file = "ch.png" },
    { code = "ci", name = "côte d'ivoire (ivory coast)", file = "ci.png" },
    { code = "ck", name = "cook islands", file = "ck.png" },
    { code = "cl", name = "chile", file = "cl.png" },
    { code = "cm", name = "cameroon", file = "cm.png" },
    { code = "cn", name = "china", file = "cn.png" },
    { code = "co", name = "colombia", file = "co.png" },
    { code = "cr", name = "costa rica", file = "cr.png" },
    { code = "cu", name = "cuba", file = "cu.png" },
    { code = "cv", name = "cape verde", file = "cv.png" },
    { code = "cw", name = "curaçao", file = "cw.png" },
    { code = "cx", name = "christmas island", file = "cx.png" },
    { code = "cy", name = "cyprus", file = "cy.png" },
    { code = "cz", name = "czechia", file = "cz.png" },
    { code = "de", name = "germany", file = "de.png" },
    { code = "dj", name = "djibouti", file = "dj.png" },
    { code = "dk", name = "denmark", file = "dk.png" },
    { code = "dm", name = "dominica", file = "dm.png" },
    { code = "do", name = "dominican republic", file = "do.png" },
    { code = "dz", name = "algeria", file = "dz.png" },
    { code = "ec", name = "ecuador", file = "ec.png" },
    { code = "ee", name = "estonia", file = "ee.png" },
    { code = "eg", name = "egypt", file = "eg.png" },
    { code = "eh", name = "western sahara", file = "eh.png" },
    { code = "er", name = "eritrea", file = "er.png" },
    { code = "es", name = "spain", file = "es.png" },
    { code = "et", name = "ethiopia", file = "et.png" },
    { code = "fi", name = "finland", file = "fi.png" },
    { code = "fj", name = "fiji", file = "fj.png" },
    { code = "fk", name = "falkland islands", file = "fk.png" },
    { code = "fm", name = "micronesia", file = "fm.png" },
    { code = "fo", name = "faroe islands", file = "fo.png" },
    { code = "fr", name = "france", file = "fr.png" },
    { code = "ga", name = "gabon", file = "ga.png" },
    { code = "gb", name = "united kingdom", file = "gb.png" },
    { code = "gb-eng", name = "england", file = "gb-eng.png" },
    { code = "gb-nir", name = "northern ireland", file = "gb-nir.png" },
    { code = "gb-sct", name = "scotland", file = "gb-sct.png" },
    { code = "gb-wls", name = "wales", file = "gb-wls.png" },
    { code = "gd", name = "grenada", file = "gd.png" },
    { code = "ge", name = "georgia", file = "ge.png" },
    { code = "gf", name = "french guiana", file = "gf.png" },
    { code = "gg", name = "guernsey", file = "gg.png" },
    { code = "gh", name = "ghana", file = "gh.png" },
    { code = "gi", name = "gibraltar", file = "gi.png" },
    { code = "gl", name = "greenland", file = "gl.png" },
    { code = "gm", name = "gambia", file = "gm.png" },
    { code = "gn", name = "guinea", file = "gn.png" },
    { code = "gp", name = "guadeloupe", file = "gp.png" },
    { code = "gq", name = "equatorial guinea", file = "gq.png" },
    { code = "gr", name = "greece", file = "gr.png" },
    { code = "gs", name = "south georgia", file = "gs.png" },
    { code = "gt", name = "guatemala", file = "gt.png" },
    { code = "gu", name = "guam", file = "gu.png" },
    { code = "gw", name = "guinea-bissau", file = "gw.png" },
    { code = "gy", name = "guyana", file = "gy.png" },
    { code = "hk", name = "hong kong", file = "hk.png" },
    { code = "hm", name = "heard island and mcdonald islands", file = "hm.png" },
    { code = "hn", name = "honduras", file = "hn.png" },
    { code = "hr", name = "croatia", file = "hr.png" },
    { code = "ht", name = "haiti", file = "ht.png" },
    { code = "hu", name = "hungary", file = "hu.png" },
    { code = "id", name = "indonesia", file = "id.png" },
    { code = "ie", name = "ireland", file = "ie.png" },
    { code = "il", name = "israel", file = "il.png" },
    { code = "im", name = "isle of man", file = "im.png" },
    { code = "in", name = "india", file = "in.png" },
    { code = "io", name = "british indian ocean territory", file = "io.png" },
    { code = "iq", name = "iraq", file = "iq.png" },
    { code = "ir", name = "iran", file = "ir.png" },
    { code = "is", name = "iceland", file = "is.png" },
    { code = "it", name = "italy", file = "it.png" },
    { code = "je", name = "jersey", file = "je.png" },
    { code = "jm", name = "jamaica", file = "jm.png" },
    { code = "jo", name = "jordan", file = "jo.png" },
    { code = "jp", name = "japan", file = "jp.png" },
    { code = "ke", name = "kenya", file = "ke.png" },
    { code = "kg", name = "kyrgyzstan", file = "kg.png" },
    { code = "kh", name = "cambodia", file = "kh.png" },
    { code = "ki", name = "kiribati", file = "ki.png" },
    { code = "km", name = "comoros", file = "km.png" },
    { code = "kn", name = "saint kitts and nevis", file = "kn.png" },
    { code = "kp", name = "north korea", file = "kp.png" },
    { code = "kr", name = "south korea", file = "kr.png" },
    { code = "kw", name = "kuwait", file = "kw.png" },
    { code = "ky", name = "cayman islands", file = "ky.png" },
    { code = "kz", name = "kazakhstan", file = "kz.png" },
    { code = "la", name = "laos", file = "la.png" },
    { code = "lb", name = "lebanon", file = "lb.png" },
    { code = "lc", name = "saint lucia", file = "lc.png" },
    { code = "li", name = "liechtenstein", file = "li.png" },
    { code = "lk", name = "sri lanka", file = "lk.png" },
    { code = "lr", name = "liberia", file = "lr.png" },
    { code = "ls", name = "lesotho", file = "ls.png" },
    { code = "lt", name = "lithuania", file = "lt.png" },
    { code = "lu", name = "luxembourg", file = "lu.png" },
    { code = "lv", name = "latvia", file = "lv.png" },
    { code = "ly", name = "libya", file = "ly.png" },
    { code = "ma", name = "morocco", file = "ma.png" },
    { code = "mc", name = "monaco", file = "mc.png" },
    { code = "md", name = "moldova", file = "md.png" },
    { code = "me", name = "montenegro", file = "me.png" },
    { code = "mf", name = "saint martin", file = "mf.png" },
    { code = "mg", name = "madagascar", file = "mg.png" },
    { code = "mh", name = "marshall islands", file = "mh.png" },
    { code = "mk", name = "north macedonia", file = "mk.png" },
    { code = "ml", name = "mali", file = "ml.png" },
    { code = "mm", name = "myanmar", file = "mm.png" },
    { code = "mn", name = "mongolia", file = "mn.png" },
    { code = "mo", name = "macau", file = "mo.png" },
    { code = "mp", name = "northern mariana islands", file = "mp.png" },
    { code = "mq", name = "martinique", file = "mq.png" },
    { code = "mr", name = "mauritania", file = "mr.png" },
    { code = "ms", name = "montserrat", file = "ms.png" },
    { code = "mt", name = "malta", file = "mt.png" },
    { code = "mu", name = "mauritius", file = "mu.png" },
    { code = "mv", name = "maldives", file = "mv.png" },
    { code = "mw", name = "malawi", file = "mw.png" },
    { code = "mx", name = "mexico", file = "mx.png" },
    { code = "my", name = "malaysia", file = "my.png" },
    { code = "mz", name = "mozambique", file = "mz.png" },
    { code = "na", name = "namibia", file = "na.png" },
    { code = "nc", name = "new caledonia", file = "nc.png" },
    { code = "ne", name = "niger", file = "ne.png" },
    { code = "nf", name = "norfolk island", file = "nf.png" },
    { code = "ng", name = "nigeria", file = "ng.png" },
    { code = "ni", name = "nicaragua", file = "ni.png" },
    { code = "nl", name = "netherlands", file = "nl.png" },
    { code = "no", name = "norway", file = "no.png" },
    { code = "np", name = "nepal", file = "np.png" },
    { code = "nr", name = "nauru", file = "nr.png" },
    { code = "nu", name = "niue", file = "nu.png" },
    { code = "nz", name = "new zealand", file = "nz.png" },
    { code = "om", name = "oman", file = "om.png" },
    { code = "pa", name = "panama", file = "pa.png" },
    { code = "pe", name = "peru", file = "pe.png" },
    { code = "pf", name = "french polynesia", file = "pf.png" },
    { code = "pg", name = "papua new guinea", file = "pg.png" },
    { code = "ph", name = "philippines", file = "ph.png" },
    { code = "pk", name = "pakistan", file = "pk.png" },
    { code = "pl", name = "poland", file = "pl.png" },
    { code = "pm", name = "saint pierre and miquelon", file = "pm.png" },
    { code = "pn", name = "pitcairn islands", file = "pn.png" },
    { code = "pr", name = "puerto rico", file = "pr.png" },
    { code = "ps", name = "palestine", file = "ps.png" },
    { code = "pt", name = "portugal", file = "pt.png" },
    { code = "pw", name = "palau", file = "pw.png" },
    { code = "py", name = "paraguay", file = "py.png" },
    { code = "qa", name = "qatar", file = "qa.png" },
    { code = "re", name = "réunion", file = "re.png" },
    { code = "ro", name = "romania", file = "ro.png" },
    { code = "rs", name = "serbia", file = "rs.png" },
    { code = "ru", name = "russia", file = "ru.png" },
    { code = "rw", name = "rwanda", file = "rw.png" },
    { code = "sa", name = "saudi arabia", file = "sa.png" },
    { code = "sb", name = "solomon islands", file = "sb.png" },
    { code = "sc", name = "seychelles", file = "sc.png" },
    { code = "sd", name = "sudan", file = "sd.png" },
    { code = "se", name = "sweden", file = "se.png" },
    { code = "sg", name = "singapore", file = "sg.png" },
    { code = "sh", name = "saint helena, ascension and tristan da cunha", file = "sh.png" },
    { code = "si", name = "slovenia", file = "si.png" },
    { code = "sj", name = "svalbard and jan mayen", file = "sj.png" },
    { code = "sk", name = "slovakia", file = "sk.png" },
    { code = "sl", name = "sierra leone", file = "sl.png" },
    { code = "sm", name = "san marino", file = "sm.png" },
    { code = "sn", name = "senegal", file = "sn.png" },
    { code = "so", name = "somalia", file = "so.png" },
    { code = "sr", name = "suriname", file = "sr.png" },
    { code = "ss", name = "south sudan", file = "ss.png" },
    { code = "st", name = "são tomé and príncipe", file = "st.png" },
    { code = "sv", name = "el salvador", file = "sv.png" },
    { code = "sx", name = "sint maarten", file = "sx.png" },
    { code = "sy", name = "syria", file = "sy.png" },
    { code = "sz", name = "eswatini (swaziland)", file = "sz.png" },
    { code = "tc", name = "turks and caicos islands", file = "tc.png" },
    { code = "td", name = "chad", file = "td.png" },
    { code = "tf", name = "french southern and antarctic lands", file = "tf.png" },
    { code = "tg", name = "togo", file = "tg.png" },
    { code = "th", name = "thailand", file = "th.png" },
    { code = "tj", name = "tajikistan", file = "tj.png" },
    { code = "tk", name = "tokelau", file = "tk.png" },
    { code = "tl", name = "timor-leste", file = "tl.png" },
    { code = "tm", name = "turkmenistan", file = "tm.png" },
    { code = "tn", name = "tunisia", file = "tn.png" },
    { code = "to", name = "tonga", file = "to.png" },
    { code = "tr", name = "turkey", file = "tr.png" },
    { code = "tt", name = "trinidad and tobago", file = "tt.png" },
    { code = "tv", name = "tuvalu", file = "tv.png" },
    { code = "tw", name = "taiwan", file = "tw.png" },
    { code = "tz", name = "tanzania", file = "tz.png" },
    { code = "ua", name = "ukraine", file = "ua.png" },
    { code = "ug", name = "uganda", file = "ug.png" },
    { code = "um", name = "united states minor outlying islands", file = "um.png" },
    { code = "us", name = "united states", file = "us.png" },
    { code = "uy", name = "uruguay", file = "uy.png" },
    { code = "uz", name = "uzbekistan", file = "uz.png" },
    { code = "va", name = "vatican city (holy see)", file = "va.png" },
    { code = "vc", name = "saint vincent and the grenadines", file = "vc.png" },
    { code = "ve", name = "venezuela", file = "ve.png" },
    { code = "vg", name = "british virgin islands", file = "vg.png" },
    { code = "vi", name = "united states virgin islands", file = "vi.png" },
    { code = "vn", name = "vietnam", file = "vn.png" },
    { code = "vu", name = "vanuatu", file = "vu.png" },
    { code = "wf", name = "wallis and futuna", file = "wf.png" },
    { code = "ws", name = "samoa", file = "ws.png" },
    { code = "xk", name = "kosovo", file = "xk.png" },
    { code = "ye", name = "yemen", file = "ye.png" },
    { code = "yt", name = "mayotte", file = "yt.png" },
    { code = "za", name = "south africa", file = "za.png" },
    { code = "zm", name = "zambia", file = "zm.png" },
    { code = "zw", name = "zimbabwe", file = "zw.png" },
}
